# Generated by Django 3.2 on 2021-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seasonratesetup',
        ),
    ]
